{{- range $name, $component := ((include "llamacloud.components" .) | fromYaml ) }}
{{- $componentPrefix := $component.prefix }}
{{- $params := dict "component" $component "root" $ }}
{{- if (include (printf "%s.secret" $componentPrefix) $params) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ print $component.name | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{ include "llamacloud.labels" (dict "name" $component.name "root" $) | indent 4 }}
  annotations: {{ include "llamacloud.annotations" (dict "component" $component "root" $) | indent 4 }}
data: {{ include (printf "%s.secret" $componentPrefix) $params | indent 2 }}
{{- end }}
{{- end }}
