{{- range $name, $component := ((include "llamacloud.components" .) | fromYaml ) }}
{{- $componentPrefix := $component.prefix }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ print $component.name | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{ include "llamacloud.labels" (dict "name" $component.name "root" $) | indent 4 }}
  annotations: {{ include "llamacloud.annotations" (dict "component" $component "root" $) | indent 4 }}
    {{- if $component.serviceAccountAnnotations }}
    {{- $component.serviceAccountAnnotations | toYaml | nindent 4 }}
    {{- end }}
{{- end }}