apiVersion: v1
kind: Secret
metadata:
  name: bucket-secret
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{ include "llamacloud.labels" (dict "root" $) | indent 4 }}
  annotations: {{ include "llamacloud.annotations" (dict "root" $) | indent 4 }}
data:
  {{- range $name, $value := .Values.config.storageBuckets.extraEnvVariables }}
  {{ $name }}: {{ $value | b64enc | quote }}
  {{- end }}