{{- if and (((.Values.config).llms).awsBedrock).accessKeyId (((.Values.config).llms).awsBedrock).secretAccessKey (((.Values.config).llms).awsBedrock).region }}
apiVersion: v1
kind: Secret
metadata:
  name: aws-bedrock-api-key-secret
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{ include "llamacloud.labels" (dict "root" $) | indent 4 }}
  annotations: {{ include "llamacloud.annotations" (dict "root" $) | indent 4 }}
data:
  AWS_BEDROCK_ENABLED: {{ "true" | b64enc | quote }}
  AWS_BEDROCK_REGION: {{ (((.Values.config).llms).awsBedrock).region | b64enc | quote }}
  AWS_BEDROCK_ACCESS_KEY_ID: {{ (((.Values.config).llms).awsBedrock).accessKeyId | b64enc | quote }}
  AWS_BEDROCK_SECRET_ACCESS_KEY: {{ (((.Values.config).llms).awsBedrock).secretAccessKey | b64enc | quote }}
  AWS_BEDROCK_SONNET_3_5_MODEL_VERSION_NAME: {{ (((.Values.config).llms).awsBedrock).sonnet3_5ModelVersionName | default "" | b64enc | quote }}
  AWS_BEDROCK_SONNET_3_7_MODEL_VERSION_NAME: {{ (((.Values.config).llms).awsBedrock).sonnet3_7ModelVersionName | default "" | b64enc | quote }}
  AWS_BEDROCK_SONNET_4_0_MODEL_VERSION_NAME: {{ (((.Values.config).llms).awsBedrock).sonnet4_0ModelVersionName | default "" | b64enc | quote }}
  AWS_BEDROCK_SONNET_4_5_MODEL_VERSION_NAME: {{ (((.Values.config).llms).awsBedrock).sonnet4_5ModelVersionName | default "" | b64enc | quote }}
  AWS_BEDROCK_HAIKU_3_5_MODEL_VERSION_NAME: {{ (((.Values.config).llms).awsBedrock).haiku3_5ModelVersionName | default "" | b64enc | quote }}
  AWS_BEDROCK_HAIKU_4_5_MODEL_VERSION_NAME: {{ (((.Values.config).llms).awsBedrock).haiku4_5ModelVersionName | default "" | b64enc | quote }}
  BEDROCK_ANTHROPIC_SONNET_3_5_VERSION_NAME: {{ (((.Values.config).llms).awsBedrock).sonnet3_5ModelVersionName | default "" | b64enc | quote }}
  BEDROCK_ANTHROPIC_SONNET_3_7_VERSION_NAME: {{ (((.Values.config).llms).awsBedrock).sonnet3_7ModelVersionName | default "" | b64enc | quote }}
  BEDROCK_ANTHROPIC_SONNET_4_0_VERSION_NAME: {{ (((.Values.config).llms).awsBedrock).sonnet4_0ModelVersionName | default "" | b64enc | quote }}
  BEDROCK_ANTHROPIC_SONNET_4_5_VERSION_NAME: {{ (((.Values.config).llms).awsBedrock).sonnet4_5ModelVersionName | default "" | b64enc | quote }}
  BEDROCK_ANTHROPIC_HAIKU_3_5_VERSION_NAME: {{ (((.Values.config).llms).awsBedrock).haiku3_5ModelVersionName | default "" | b64enc | quote }}
  BEDROCK_ANTHROPIC_HAIKU_4_5_VERSION_NAME: {{ (((.Values.config).llms).awsBedrock).haiku4_5ModelVersionName | default "" | b64enc | quote }}
  BEDROCK_ANTHROPIC_SONNET_3_5_MODEL_ID: {{ (((.Values.config).llms).awsBedrock).sonnet3_5ModelVersionName | default "" | b64enc | quote }}
  BEDROCK_ANTHROPIC_SONNET_3_7_MODEL_ID: {{ (((.Values.config).llms).awsBedrock).sonnet3_7ModelVersionName | default "" | b64enc | quote }}
  BEDROCK_ANTHROPIC_SONNET_4_0_MODEL_ID: {{ (((.Values.config).llms).awsBedrock).sonnet4_0ModelVersionName | default "" | b64enc | quote }}
  BEDROCK_ANTHROPIC_SONNET_4_5_MODEL_ID: {{ (((.Values.config).llms).awsBedrock).sonnet4_5ModelVersionName | default "" | b64enc | quote }}
  BEDROCK_ANTHROPIC_HAIKU_3_5_MODEL_ID: {{ (((.Values.config).llms).awsBedrock).haiku3_5ModelVersionName | default "" | b64enc | quote }}
  BEDROCK_ANTHROPIC_HAIKU_4_5_MODEL_ID: {{ (((.Values.config).llms).awsBedrock).haiku4_5ModelVersionName | default "" | b64enc | quote }}
{{ end }}