{{- if (((.Values.config).llms).providerConfigs) }}
apiVersion: v1
kind: Secret
metadata:
  name: llm-provider-configs-secret
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{ include "llamacloud.labels" (dict "root" $) | indent 4 }}
  annotations: {{ include "llamacloud.annotations" (dict "root" $) | indent 4 }}
data:
  LLM_PROVIDER_CONFIGS_JSON: {{ (((.Values.config).llms).providerConfigs) | toJson | b64enc | quote }}
{{- end }}
