{{- if (((.Values.config).llms).anthropic).apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: anthropic-api-key-secret
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{ include "llamacloud.labels" (dict "root" $) | indent 4 }}
  annotations: {{ include "llamacloud.annotations" (dict "root" $) | indent 4 }}
data:
  ANTHROPIC_API_KEY: {{ (((.Values.config).llms).anthropic).apiKey | b64enc | quote }}
{{- end }}