{{- if (((.Values.config).llms).gemini).apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: gemini-api-key-secret
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{ include "llamacloud.labels" (dict "root" $) | indent 4 }}
  annotations: {{ include "llamacloud.annotations" (dict "root" $) | indent 4 }}
data:
  GOOGLE_GEMINI_API_KEY: {{ (((.Values.config).llms).gemini).apiKey | b64enc | quote }}
{{- end }}