{{- if (((.Values.config).llms).openAi).apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: openai-api-key-secret
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{ include "llamacloud.labels" (dict "root" $) | indent 4 }}
  annotations: {{ include "llamacloud.annotations" (dict "root" $) | indent 4 }}
data:
  OPENAI_API_KEY: {{ (((.Values.config).llms).openAi).apiKey | b64enc | quote }}
  LC_OPENAI_API_KEY: {{ (((.Values.config).llms).openAi).apiKey | b64enc | quote }}
  EVAL_OPENAI_API_KEY: {{ (((.Values.config).llms).openAi).apiKey | b64enc | quote }}
  {{- if (((.Values.config).llms).openAi).baseUrl }}
  OPENAI_BASE_URL: {{ (((.Values.config).llms).openAi).baseUrl | b64enc | quote }}
  {{- end }}
{{- end }}