{{- if and (((.Values.config).llms).googleVertexAi).projectId (((.Values.config).llms).googleVertexAi).credentialsJson (((.Values.config).llms).googleVertexAi).location }}
apiVersion: v1
kind: Secret
metadata:
  name: google-vertex-ai-api-key-secret
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{ include "llamacloud.labels" (dict "root" $) | indent 4 }}
  annotations: {{ include "llamacloud.annotations" (dict "root" $) | indent 4 }}
data:
  GOOGLE_VERTEX_AI_ENABLED: {{ "true" | b64enc | quote }}
  GOOGLE_VERTEX_AI_PROJECT_ID: {{ (((.Values.config).llms).googleVertexAi).projectId | b64enc | quote }}
  GOOGLE_VERTEX_AI_LOCATION: {{ (((.Values.config).llms).googleVertexAi).location | b64enc | quote }}
  GOOGLE_VERTEX_AI_CREDENTIALS_JSON: {{ (((.Values.config).llms).googleVertexAi).credentialsJson | b64enc | quote }}
{{ end }}