{{- if not (eq .Values.config.storageBuckets.provider "aws") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: s3proxy-secret
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{ include "llamacloud.labels" (dict "root" $) | indent 4 }}
  annotations: {{ include "llamacloud.annotations" (dict "root" $) | indent 4 }}
data:
  {{- include "llamacloud.s3proxy.secret" . | nindent 2 }}
{{- end }}
